### ISSUE TITLE
Button Click detection consistently missing button pushes 

### ISSUE THREAD

**Issue by kenj1** [Move38/Move38-Arduino-Platform#37]
A game I'm writing was consistently missing button pushes.  So I wrote this simple program and proved the point.  If you press and release the button in slightly less than 1 second intervals, than no button clicks are registered.  However, you will receive buttonRelease indications without a button press being acknowledged.  I put timestamps (millis()) and appropriate text in the output so the missed button presses are visible.  It's my expectation that a buttonRelease indication should not be true if there was not a prior button press indication.

[brokenButtonsProgram.txt](https://github.com/Move38/Move38-Arduino-Platform/files/2354702/brokenButtonsProgram.txt)

The Serial Port output below.  The first value in the log statements is the millis() value.

7357 buttonReleased  MISSED PRESS: : buttonClickCount=0
11904: buttonSingleClicked
11904 buttonReleased : buttonClickCount=1
18862: buttonSingleClicked
18862 buttonReleased : buttonClickCount=1
21073 buttonReleased  MISSED PRESS: : buttonClickCount=0
23510 buttonReleased  MISSED PRESS: : buttonClickCount=0
27709 buttonReleased  MISSED PRESS: : buttonClickCount=0
29153: buttonSingleClicked
29153 buttonReleased : buttonClickCount=1
30544: buttonSingleClicked
30544 buttonReleased : buttonClickCount=1
31672: buttonSingleClicked
31672 buttonReleased : buttonClickCount=1
31887 buttonReleased  MISSED PRESS: : buttonClickCount=0
35712: buttonDoubleClicked
35712 buttonReleased : buttonClickCount=2
35911 buttonReleased  MISSED PRESS: : buttonClickCount=0

**Comment by kenj1** [comment]
Here's an updated program that shows the buttonPress but no button clicks are ever registered.  I believe the issue is in the button debounce handling (timing issue between that and the click window countdown)...  The result of the test showing the problem is at the end of this comment.
------------- UPDATED BUTTON DETECTION ----------
#include "blinklib.h"
#include "blinkstate.h"
#include "Serial.h"

ServicePortSerial sp;

void setup() {
  // put your setup code here, to run once:
  sp.begin(500000);
}

void loop() {
  // put your main code here, to run repeatedly:
  bool buttonClickDetected = false;
  
  if (buttonReleased()) {
      if(buttonSingleClicked()) {
        buttonClickDetected = true;
        sp.print(millis());
        sp.println(": buttonSingleClicked");
      }
      if (buttonDoubleClicked()) {
        buttonClickDetected = true;
        sp.print(millis());
        sp.println(": buttonDoubleClicked");
      } 
      if (buttonLongPressed()) {
        buttonClickDetected = true;
        sp.print(millis());
        sp.println(": buttonLongPressed");
      }
      if (buttonMultiClicked()) {
        buttonClickDetected = true;
        sp.print(millis());
        sp.println(": buttonMultiClicked");        
      }
      if(buttonPressed()) {
        sp.print(millis());
        sp.println(": buttonPressed");     
      }
    sp.print(millis());
    sp.print(" buttonReleased ");
    if(!buttonClickDetected)
      sp.print(" MISSED CLICK: ");
    sp.print(": buttonClickCount=");
    sp.println(buttonClickCount());
  }
}
---------- PROGRAM END ------------
--------- TEST RESULTS -----------
12364 buttonReleased  MISSED CLICK: : buttonClickCount=0
17187: buttonSingleClicked
17187: buttonPressed
17187 buttonReleased : buttonClickCount=1
21672: buttonSingleClicked
21672: buttonPressed
21672 buttonReleased : buttonClickCount=1
23347: buttonSingleClicked
23347: buttonPressed
23347 buttonReleased : buttonClickCount=1
24954: buttonPressed
24954 buttonReleased  MISSED CLICK: : buttonClickCount=0
26244: buttonPressed
26244 buttonReleased  MISSED CLICK: : buttonClickCount=0
27463: buttonPressed
27463 buttonReleased  MISSED CLICK: : buttonClickCount=0
28677: buttonPressed
28677 buttonReleased  MISSED CLICK: : buttonClickCount=0

**Comment by kenj1** [comment]
Here's the forum discussion on this issue:

http://forum.move38.com/t/blink-button-presses-consistently-missed/121

**Comment by bigjosh** [comment]
This was fixed a year ago in my repo! :) ..

https://github.com/bigjosh/Move38-Arduino-Platform/commit/394b0019e41a2c185083276c674753b9c2ae88dc

Working now to get all my changes into the move38 repo... !

**Comment by jbobrow** [comment]
@kenj1 Dev branch is quickly evolving, changes will be merged to master soon, but feel free to join us on dev. Need some more testers of some very early game transmission :)
